-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "currency" DROP DEFAULT,
ALTER COLUMN "start_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "billing_period" DROP DEFAULT,
ALTER COLUMN "next_payment_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "status" DROP DEFAULT;
