/*
  Warnings:

  - The values [QUERTERLY] on the enum `SUBSCRIPTION_BILLING_PERIOD` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "SUBSCRIPTION_BILLING_PERIOD_new" AS ENUM ('MONTHLY', 'QUARTERLY', 'YEARLY');
ALTER TABLE "Subscription" ALTER COLUMN "billing_period" DROP DEFAULT;
ALTER TABLE "Subscription" ALTER COLUMN "billing_period" TYPE "SUBSCRIPTION_BILLING_PERIOD_new" USING ("billing_period"::text::"SUBSCRIPTION_BILLING_PERIOD_new");
ALTER TYPE "SUBSCRIPTION_BILLING_PERIOD" RENAME TO "SUBSCRIPTION_BILLING_PERIOD_old";
ALTER TYPE "SUBSCRIPTION_BILLING_PERIOD_new" RENAME TO "SUBSCRIPTION_BILLING_PERIOD";
DROP TYPE "SUBSCRIPTION_BILLING_PERIOD_old";
ALTER TABLE "Subscription" ALTER COLUMN "billing_period" SET DEFAULT 'MONTHLY';
COMMIT;
